name: CI (Windows)
on:
  workflow_call:
jobs:
  build:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Restore build files
      uses: actions/cache/restore@v3
      with:
        path: target
        key: ${{ runner.os }}-build-files-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}
    - name: Build
      run: cargo build --release
    - name: Run Clippy
      run: cargo clippy --release
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: amplibot-win64
        path: target/release
    - name: Cache build files
      uses: actions/cache/save@v3
      with:
        path: target
        key: ${{ runner.os }}-build-files-${{ hashFiles('**/Cargo.toml', '**/Cargo.lock') }}-${{ github.run_id }}
      if: startsWith(github.ref, 'refs/heads/')