name: Main Build Starter
on:
  push:
    branches:
    - main
concurrency: dev-${{ github.ref }}
jobs:
  windows:
    name: Build
    uses: ./.github/workflows/ci-windows.yml
  mac:
    name: Build
    uses: ./.github/workflows/ci-mac.yml
  linux:
    name: Build
    uses: ./.github/workflows/ci-linux.yml